Add `withCredentials` option to the `auth` config to support CORS
looker-open-source/embed-sdk pull request #68
Opened 2021-03-16 19:56 UTC by brettjonesdev

## [Issue](Implementation of https://github.com/looker-open-source/embed-sdk/issues/67)
Currently, there is no way to indicate to tell the Embed SDK to include Http Only request headers in the Auth endpoint `XmlHttpRequest` that is created to authenticate a user and generate a signed SSO embed url when the auth endpoint lives on a different domain than the host site. 

## Solution
This PR adds a `withCredentials` configuration option to the existing `auth` config object, allowing the user to set `xhr.withCredentials = true`, which will allow secure Http Only Cookies to set request headers on the auth requests.

2021-03-16 23:25 UTC, izzymiller commented
Hey Brett, thanks for the PR! Overall I think this looks good, but i tagged in an expert to review. Before we can merge, you'll have to sign a google CLA, which is pretty easy: https://cla.developers.google.com/.

2021-03-16 23:57 UTC, brettjonesdev commented
Thanks, @izzymiller! Allie Janoch our CEO just signed the CLA. Lmk if you need anything more on my end!

2021-03-24 02:39 UTC, brettjonesdev commented
@izzymiller any update on this? Would love to be able to ship our V1 without using my own fork haha.

2021-03-24 04:11 UTC, izzymiller commented
Thanks for the ping. Looks like I tagged a reviewer who's OOO, woops!

2021-03-24 04:30 UTC, izzymiller requested changes
Small change requested to the documentation to make the example correct, but other than that this looks good to me. 

Thanks for contributing, and for writing a test and docs for your addition. We really appreciate it :)

2021-03-24 04:30 UTC, izzymiller commented on README.md
> +    params: { foo: 'bar' },
Believe these need to be arrays of objects w/ a specific shape `Array<{name: string, value: string}>` like so: 
```suggestion
    headers: [{'name': 'Foo Header', 'value': 'Foo'}],
    params: [{'name': 'foo', 'value': 'bar'}],
```

2021-03-29 20:32 UTC, brettjonesdev commented
Committed those changes, thanks @izzymiller!

2021-03-29 20:36 UTC, izzymiller approved these changes

2021-03-29 20:37 UTC, merged